name: app_music1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^6.6.0
  google_fonts: ^8.1.0
  xml: ^6.3.0
  file_picker: ^11.0.2
  path_provider: ^2.1.5
  provider: ^6.0.0
  logger: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    # Si no existe sample.musicxml, coméntalo o elimínalo
    # - assets/sample.musicxml
    - musicxml_preload/
    
    # Ejercicios numerados organizados por nivel
    - assets/exercises/
    - assets/exercises/inicial/
    - assets/exercises/intermedio/
    - assets/exercises/avanzado/

  fonts:
    - family: Bravura
      fonts:
        - asset: assets/fonts/Bravura.otf